### ISSUE TITLE
Naloge in rešitve - Povezave med kotnimi funkcijami in adicijski izreki

### ISSUE THREAD

**Issue by Kataja20** [andrejbauer/vaje-iz-funkcij#17]
- [ ] 1 naloga izračuna preostalih kotnih funkcij (sin podan, ostale se izračuna)

- [ ]  3 nalogi poenostavitve izrazov

Pred vsakim tipom nalog je en zgled reševanja.

**Comment by andrejbauer** [comment]
Tole bi razbil na dve ločeni zadevi, da lahko vsako posebej potem zapreš.

**Comment by andrejbauer** [comment]
Razdeljeno na zadeve #22, #23
