### ISSUE TITLE
Naloge in rešitve - Grafi kotnih funkcij 

### ISSUE THREAD

**Issue by emacesek1** [andrejbauer/vaje-iz-funkcij#18]
- [ ] zgled risanja grafov 

- [ ] 2 enostavnejši nalogi risanja grafov brez premikov

- [ ] 2 tezji nalogi risanje grafov s premiki

**Comment by andrejbauer** [comment]
Jaz bi tole razbil na tri ločene zadeve, tako da lahko potem vsako posebej zapreš, ko narediš zgled in naloge.

**Comment by andrejbauer** [comment]
Zadevo sem razbil na #19, #20 in #21.
