### ISSUE TITLE
Pregled polinomov

### ISSUE THREAD

**Issue by ninakosmrlj** [andrejbauer/vaje-iz-funkcij#4]
- [ ] Definicija ter posebni primeri polinomov
- [ ] Računske operacije s polinomi in osnovni izrek o deljenju polinomov
- [ ] Razcep ter iskanje ničel polinoma (metoda bisekcije, Hornerjev algoritem)
- [ ] Risanje grafa (ničle, začetna vrednost, vodoravne tangente, oblika polinoma v neskončnosti)

**Comment by andrejbauer** [comment]
A lahko se prosim razdeli tole na posamezne zadeve, kjer se bolj natančno opredeli, kaj se bo delalo?
