### ISSUE TITLE
Naloge in rešitve nalog o polinomih

### ISSUE THREAD

**Issue by ninakosmrlj** [andrejbauer/vaje-iz-funkcij#6]
- [ ] Računske operacije s polinomi (1 naloga)
- [ ] Osnovni izrek o deljenju polinomov (1 naloga)
- [ ] Razcep polinoma in Hornerjev algoritem (zgled+3 naloge)
- [ ] Risanje grafa polinoma-ničle, začetna vrednost, vrednost polinoma v točki˙(zgled+2 nalogi)
- [ ] Ekstremi polinoma v povezavi z odvodom (zgled+2 nalogi)
- [ ] Enačba tangente v točki na graf polinoma (zgled+2 nalogi)

**Comment by andrejbauer** [comment]
Poglejte si mejnik [Koten funkcije](https://github.com/andrejbauer/vaje-iz-funkcij/milestone/4), kjer sem zadeve razbil na veliko manjših zadev. Tudi v tem mejniku prosim razbijte tole develo zadevo na več manjših, ki jih potem lahko zapirate eno po eno. Ko bote sto naredili, tu naštejete vse nove zadeve, ki so nastale iz te in to zadevo zaprete.
